
logging.level.root=INFO
logging.level.org.hibernate=OFF
logging.level.org.quartz=OFF
log4j.logger.org.quartz=OFF
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.show_sql=false
org.quartz=OFF